/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.testcontainers.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ModeloAvro3 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8684382045625255146L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ModeloAvro3\",\"namespace\":\"com.testcontainers.avro\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"descricao\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ModeloAvro3> ENCODER =
      new BinaryMessageEncoder<ModeloAvro3>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ModeloAvro3> DECODER =
      new BinaryMessageDecoder<ModeloAvro3>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ModeloAvro3> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ModeloAvro3> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ModeloAvro3> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ModeloAvro3>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ModeloAvro3 to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ModeloAvro3 from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ModeloAvro3 instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ModeloAvro3 fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String id;
  private java.lang.String descricao;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ModeloAvro3() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param descricao The new value for descricao
   */
  public ModeloAvro3(java.lang.String id, java.lang.String descricao) {
    this.id = id;
    this.descricao = descricao;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return descricao;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = value$ != null ? value$.toString() : null; break;
    case 1: descricao = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'descricao' field.
   * @return The value of the 'descricao' field.
   */
  public java.lang.String getDescricao() {
    return descricao;
  }


  /**
   * Sets the value of the 'descricao' field.
   * @param value the value to set.
   */
  public void setDescricao(java.lang.String value) {
    this.descricao = value;
  }

  /**
   * Creates a new ModeloAvro3 RecordBuilder.
   * @return A new ModeloAvro3 RecordBuilder
   */
  public static com.testcontainers.avro.ModeloAvro3.Builder newBuilder() {
    return new com.testcontainers.avro.ModeloAvro3.Builder();
  }

  /**
   * Creates a new ModeloAvro3 RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ModeloAvro3 RecordBuilder
   */
  public static com.testcontainers.avro.ModeloAvro3.Builder newBuilder(com.testcontainers.avro.ModeloAvro3.Builder other) {
    if (other == null) {
      return new com.testcontainers.avro.ModeloAvro3.Builder();
    } else {
      return new com.testcontainers.avro.ModeloAvro3.Builder(other);
    }
  }

  /**
   * Creates a new ModeloAvro3 RecordBuilder by copying an existing ModeloAvro3 instance.
   * @param other The existing instance to copy.
   * @return A new ModeloAvro3 RecordBuilder
   */
  public static com.testcontainers.avro.ModeloAvro3.Builder newBuilder(com.testcontainers.avro.ModeloAvro3 other) {
    if (other == null) {
      return new com.testcontainers.avro.ModeloAvro3.Builder();
    } else {
      return new com.testcontainers.avro.ModeloAvro3.Builder(other);
    }
  }

  /**
   * RecordBuilder for ModeloAvro3 instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ModeloAvro3>
    implements org.apache.avro.data.RecordBuilder<ModeloAvro3> {

    private java.lang.String id;
    private java.lang.String descricao;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.testcontainers.avro.ModeloAvro3.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.descricao)) {
        this.descricao = data().deepCopy(fields()[1].schema(), other.descricao);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing ModeloAvro3 instance
     * @param other The existing instance to copy.
     */
    private Builder(com.testcontainers.avro.ModeloAvro3 other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.descricao)) {
        this.descricao = data().deepCopy(fields()[1].schema(), other.descricao);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.testcontainers.avro.ModeloAvro3.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.testcontainers.avro.ModeloAvro3.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'descricao' field.
      * @return The value.
      */
    public java.lang.String getDescricao() {
      return descricao;
    }


    /**
      * Sets the value of the 'descricao' field.
      * @param value The value of 'descricao'.
      * @return This builder.
      */
    public com.testcontainers.avro.ModeloAvro3.Builder setDescricao(java.lang.String value) {
      validate(fields()[1], value);
      this.descricao = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'descricao' field has been set.
      * @return True if the 'descricao' field has been set, false otherwise.
      */
    public boolean hasDescricao() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'descricao' field.
      * @return This builder.
      */
    public com.testcontainers.avro.ModeloAvro3.Builder clearDescricao() {
      descricao = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ModeloAvro3 build() {
      try {
        ModeloAvro3 record = new ModeloAvro3();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.descricao = fieldSetFlags()[1] ? this.descricao : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ModeloAvro3>
    WRITER$ = (org.apache.avro.io.DatumWriter<ModeloAvro3>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ModeloAvro3>
    READER$ = (org.apache.avro.io.DatumReader<ModeloAvro3>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










